name: Release Pipeline

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    
    env:
      publish_folder: publish

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.8.2
        with:
          dotnet-version: 5.x.x

      - name: Build
        run: dotnet publish /p:PublishSingleFile=true --framework net5.0 --self-contained --runtime linux-x64 --configuration release --output ${{ env.publish_folder }}
        
      - name: Publish
        run: |
          scp help
