name: Release Pipeline

on:
  push:
    branches: [ main ]
    
jobs:
  publish:
    runs-on: ubuntu-latest
    environment: Uberspace
    env:
      local_publish_folder: publish
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.8.2
        with:
          dotnet-version: 6.x.x

      - name: Build
        run: dotnet publish /p:PublishSingleFile=true --framework net6.0 --self-contained --runtime linux-x64 --configuration release --output ${{ env.local_publish_folder }}
        
      - name: Publish
        env:
          host: '${{ secrets.SSH_HOST }}'
          publish_path: '${{ secrets.PUBLISH_PATH }}'
          ssh_user: '${{ secrets.SSH_USERNAME }}'
          ssh_password: '${{ secrets.SSH_PASSWORD }}'
        run: |
          mkdir ~/.ssh && touch ~/.ssh/known_hosts
          ssh-keyscan -H ${{ env.host }} > ~/.ssh/known_hosts
          sshpass -p "${{ env.ssh_password }}" scp -r ${{ env.local_publish_folder }}/* ${{ env.ssh_user }}@${{ env.host }}:${{ env.publish_path }}
